# Etapa de build do frontend
FROM node:16 as build
WORKDIR /app
COPY . .
RUN npm install
RUN npm run build

# Este Dockerfile é usado para gerar o build do React.
# Não precisamos de uma etapa de desenvolvimento aqui, porque vamos servir o build estático pelo Nginx.
